export type Language = "en" | "my";

export const defaultLanguage: Language = "en";

export const labels = {
  en: {
    title: "Title",
    name: "Name",
    place: "Place",
    Highlights: "Highlights",
    location: "Location",
    date: "Date",
    pinkCard: "Pink Card",
    thai: "Thai Language",
    paymentType: "Payment Type",
    stay: "Stay",
    notes: "Notes",
    adminJobManagement: "Admin Job Management",
    noJobs: "No jobs available",
    backToDashboard: "Back to Dashboard",
    deleteConfirm: "Are you sure you want to delete this post?",
    cancel: "Cancel",
    delete: "Delete",
    add: "Add",
    edit:"Edit",
    address:"Address",
    monthly:"Monthly",
    daily:"Daily",
    addressRequired:"If stay is provided fill this field",
    
  },
  my: {
    title: "အလုပ်အမျိုးအစား",
    name: "အမည်",
    place: "နေရာ",
    highlights: "လည်ပတ်စရာ",
    location: "တည်နေရာ",
    date: "ရက်စွဲ",
    pinkCard: "ဘတ်",
    thai: "ထိုင်းစကား",
    paymentType: "ငွေပေးချေမှုအမျိုးအစား",
    stay: "နေစရာ",
    notes: "မှတ်ချက်",
    adminJobManagement: "အက်ဒမင် အလုပ်စီမံခန့်ခွဲမှု",
    noJobs: "အလုပ်များ မရှိပါ",
    backToDashboard: "ဒက်ရှ်ဘုတ်သို့ ပြန်သွားပါ",
    deleteConfirm: "သေချာပြီး ဖျက်လိုပါသလား?",
    cancel: "မဖျက်တော့ပါ",
    delete: "ဖျက်မည်",
    add: "အသစ်တင်မည်",
    edit:"ပြင်မည်",
    address: "လိပ်စာ",
    monthly:"လစား",
    daily:"နေ့စား",
    addressRequired:"(နေစရာပေးလျှင် ဖြည့်ရန်)",
  },
};