export type Language = "en" | "my";

export const defaultLanguage: Language = "en";

export const labels = {
  en: {
    title: "Title",
    name: "Name",
    place: "Place",
    highlights: "Highlights",
    location: "Location",
    date: "Date",
    pinkCard: "Pink Card",
    thai: "Thai Language",
    paymentType: "Payment Type",
    stay: "Stay",
    notes: "Notes",
    adminJobManagement: "Admin Job Management",
    noJobs: "No jobs available",
    backToDashboard: "Back to Dashboard",
    deleteConfirm: "Are you sure you want to delete this post?",
    cancel: "Cancel",
    delete: "Delete",
    add: "Add",
    edit: "Edit",
    address: "Address",
    monthly: "Monthly",
    daily: "Daily",
    addressRequired: "If stay is provided fill this field",
    images: "Images",
    rentFee: "Rent Fee:",
    services: "Services:",
    price: "Price:",
    nearby: "Nearby Places",
    amenities: "Admenities",
    nearbyPlaces: "Nearby Places",
    save: "Save",
    popular: "Popular Picks",
    adminRating: "Ratings",
    rating: "Ratings",
    duration: "Duration",
    coursename: "Name",
    courseprice: "Price",
    centreName: "Centre Name",
    adminJobs: "Admin Jobs",
    adminTravel: "Admin Travel",
    adminCondo: "Admin Condo",
    adminHotels: "Admin Hotels",
    adminDetails: "Admin Details",
    adminRestaurants: "Admin Restaurants",
    adminCourses: "Admin Courses",
    adminGeneral: "Admin General",
  },
  my: {
    title: "အလုပ်အမျိုးအစား",
    name: "အမည်",
    place: "နေရာ",
    highlights: "လည်ပတ်စရာ",
    location: "တည်နေရာ",
    date: "ရက်စွဲ",
    pinkCard: "ဘတ်",
    thai: "ထိုင်းစကား",
    paymentType: "ငွေပေးချေမှုအမျိုးအစား",
    stay: "နေစရာ",
    notes: "မှတ်ချက်",
    adminJobManagement: "အက်ဒမင် အလုပ်စီမံခန့်ခွဲမှု",
    noJobs: "အလုပ်များ မရှိပါ",
    backToDashboard: "ဒက်ရှ်ဘုတ်သို့ ပြန်သွားပါ",
    deleteConfirm: "သေချာပြီး ဖျက်လိုပါသလား?",
    cancel: "မဖျက်တော့ပါ",
    delete: "ဖျက်မည်",
    add: "အသစ်တင်မည်",
    edit: "ပြင်မည်",
    address: "လိပ်စာ",
    monthly: "လစား",
    daily: "နေ့စား",
    addressRequired: "(နေစရာပေးလျှင် ဖြည့်ရန်)",
    images: "ဓာတ်ပုံ",
    rentFee: "စျေးနှုန်း",
    services: "ဝန်ဆောင်မှုများ",
    price: "စျေးနှုန်း",
    nearby: "လည်ပတ်စရာ",
    amenities: "ဝန်ဆောင်မှုများ",
    nearbyPlaces: "လည်ပတ်စရာ",
    save: "သိမ်းမည်",
    popular: "အကောင်းဆုံးမီနူးများ",
    adminRating: "အဆင့်ပေးသက်မှတ်ချက်",
    rating: "အဆင့်ပေးသက်မှတ်ချက်",
    duration: "သင်တန်းကာလ",
    coursename: "သင်တန်းအမည်",
    courseprice: "သင်တန်းကြေး",
    centreName: "ကျောင်းအမည်",
    adminJobs: "အလုပ်အကိုင် လမ်းညွှန်",
    adminTravel: "ခရီးသွား လမ်းညွှန်",
    adminCondo: "ကွန်ဒို အခန်း လမ်းညွှန်",
    adminHotels: "ဟိုတယ် လမ်းညွှန်",
    adminDetails: "အထောက်အထား လမ်းညွှန်",
    adminRestaurants: "စားသောက်ဆိုင် လမ်းညွှန်",
    adminCourses: "သင်တန်း လမ်းညွှန်",
    adminGeneral: "အထွေထွေ လမ်းညွှန်",
  },
};